[package]
name = "origami_rating"
version.workspace = true
edition.workspace = true
description = "Rating related algorithm library for Dojo based games."
homepage = "https://github.com/dojoengine/origami/tree/main/crates/rating"

[dependencies]
cairo_test.workspace = true
