[package]
name = "origami_rating"
version.workspace = true
description = "Rating related algorithm library for Dojo based games."
homepage = "https://github.com/dojoengine/origami/tree/main/crates/rating"
edition = "2024_07"

[dependencies]
