[package]
name = "origami_algebra"
version.workspace = true
edition.workspace = true
description = "Algebra library for Dojo based games."
homepage = "https://github.com/dojoengine/origami/tree/main/crates/algebra"

[dependencies]
cubit.workspace = true

[dev-dependencies]
cairo_test.workspace = true
