name: 'Setup'
description: 'Setup tooling'
runs:
  using: "composite"
  steps:
    - name: Install dojoup
      run: curl -L https://install.dojoengine.org -v nightly | bash
      shell: bash

    - name: Install dojo
      run: |
        /home/runner/.config/.dojo/bin/dojoup --version ${{ env.DOJO_VERSION }}
        sudo mv /home/runner/.config/.dojo/bin/katana /usr/local/bin/
        sudo mv /home/runner/.config/.dojo/bin/sozo /usr/local/bin/
      shell: bash
