name: "Setup"
description: "Setup tooling"
runs:
  using: "composite"
  steps:
    - name: Install dojo
      run: |
        curl -L -o dojo-linux-x86_64.tar.gz https://github.com/dojoengine/dojo/releases/download/${{ env.DOJO_VERSION }}/dojo_${{ env.DOJO_VERSION }}_linux_amd64.tar.gz
        tar -xzf dojo-linux-x86_64.tar.gz
        sudo mv sozo /usr/local/bin/
      shell: bash
