[workspace]
members = [
    "crates/defi",
    "crates/hexmap",
    "crates/map",
    "crates/random",
    "crates/rating",
    "crates/security",
]

[workspace.package]
version = "1.8.0"
edition = "2024_07"
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/dojoengine/origami"

[workspace.dependencies]
fixed = "0.4.0"
starknet = "^2.19.4"
cairo_test = "^2.19.4"
snforge_std = "0.61.0"
