[package]
name = "origami_security"
version.workspace = true
edition.workspace = true
description = "Security library for Dojo based games."
homepage = "https://github.com/dojoengine/origami/tree/main/crates/security"

[dependencies]
cairo_test.workspace = true
