[package]
name = "origami_security"
version.workspace = true
description = "Security library for Dojo based games."
homepage = "https://github.com/dojoengine/origami/tree/main/crates/security"
edition = "2024_07"

[dependencies]
