[package]
name = "governance"
version = "0.0.0"
description = "Implementations of Compound Governance standards for the Dojo framework."
homepage = "https://github.com/dojoengine/origami/tree/governance"

[dependencies]
dojo.workspace = true

[tool.fmt]
sort-module-level-items = true

[lib]

[[target.dojo]]
