[package]
name = "origami_governance"
version.workspace = true
description = "Implementations of Compound Governance standards for the Dojo framework."
homepage = "https://github.com/dojoengine/origami/tree/governance"

[dependencies]
dojo.workspace = true

[tool.fmt]
sort-module-level-items = true

[lib]
