[package]
name = "origami_random"
version.workspace = true
description = "Random generator library for Dojo based games."
homepage = "https://github.com/dojoengine/origami/tree/main/crates/random"
edition = "2024_07"

[dependencies]
